### ISSUE TITLE
Unable to apply IN to a static @Spec 

### ISSUE THREAD

**Issue by desolate-planet** [tkaczmarzyk/specification-arg-resolver#126]
Hello, the documentation states that it's possible to apply static predicates to @Spec annotations. I tried to use the following:

 @Spec(path="journeyStatus", spec= In.class, paramSeparator=',', constVal="Apply Protections,Match Customer,Match Account,Remove Protections")

The above does not work. I basically have an enum mapped to a bunch of strings that are stored in a backing DB and I want the above to applied to return instances that match that condition.

The alternative is to have a new column called "processed" or something and use the static matcher to use that instead, but it would be nice to be able to do something like I had tried above.

**Comment by rdworak37** [comment]
Hi, I've looked over this issue and I'm pretty sure that `constVal` you're passing should be just an array instead of single string and `paramSeparator` field (as this field works only for parameters passed in URL).

Something like this should have worked
`@Spec(path="journeyStatus", spec=In.class, constVal={"Apply Protections", "Match Customer","Match Account","Remove Protections"})`

**Comment by tkaczmarzyk** [comment]
Working snippet has been provided in https://github.com/tkaczmarzyk/specification-arg-resolver/issues/104
