### ISSUE TITLE
Java 17 incompatibility 

### ISSUE THREAD

**Issue by MarceloWalther-Dev** [tkaczmarzyk/specification-arg-resolver#131]
I couldn't implement using java 17. 
Error played by console:
java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @51e2adc7
![image](https://user-images.githubusercontent.com/63797325/181086810-2b0a46eb-58b2-4384-a709-39a41b91775a.png)

![image](https://user-images.githubusercontent.com/63797325/181086849-17ec0616-59cd-4e59-b823-1ff9012a29d3.png)
![image](https://user-images.githubusercontent.com/63797325/181087020-ab45a76f-da61-4ea1-8f50-97644c744b3b.png)

**Comment by brunodigaha** [comment]
This error message is as if it couldn't access some private attribute, since it couldn't get any error signal, reflecting without meizing the attribute that needed easy access, but sometimes looking at a signal

"java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @51e2adc7"

**Comment by MarceloWalther-Dev** [comment]
I upgraded to version 2.6.3 and it worked properly.
