### ISSUE TITLE
about Annotation  in business layer

### ISSUE THREAD

**Issue by duoleimi** [tkaczmarzyk/specification-arg-resolver#4]
i want to use it in business layer.
How should I do.
Can i use `@spec` in business layer?

**Comment by CristhianUNSa** [comment]
Hi! I came across the same problem. I want it to create an automated specification (runtime spec?) from an object, which is supossed to have the properties to filter the database tables.
Something like this:
```
Specification<Person> personSpec = SpecArgResolver.resolve(PersonFilterSpec.class, personFilter);
peopleRepo.findAll(personSpec, pageable);
```
`PersonFilterSpec` would have the desired annotations, and `personFilter` the actual values. Bear in mind that this is just pseudocode, because I'm not sure if something like this is even possible.

Best regards
