### ISSUE TITLE
Specification resolver with spec In.Class not working when client send String Data

### ISSUE THREAD

**Issue by zainul-realtime** [tkaczmarzyk/specification-arg-resolver#9]
hello i am Zainul , i use specification resolver , but currently not working properly because when i use spec=In.class
my Model property type is Integer
my spec in rest controller using spec=In.class
and then
my sent request i sent String data like "ABC" resolver can't handle it  ? 
i try to ovveride and manipulate In class to dataType String in net.kaczmarzyk.spring.data.jpa.domain but always back to Integer ??

Hopefully can help me :) thanks :+1:

**Comment by tkaczmarzyk** [comment]
Hi, I'll try to help, but I'm not sure what's the expected behaviour. The property is integer, so how would you expect it to work with a value such as "ABC"? Empty result set?

**Comment by zainul-realtime** [comment]
Yes , my expected value , when i post  "ABC" is empty result

**Comment by tkaczmarzyk** [comment]
Hi Zainul, sorry for the delay.
I made a quick fix -- you can find on a new branch called "prototype".
I hope it will help you.
I need more time to make a new release, because I think that the final solution should work also for Equal.class and allow to configure the behaviour (either exception or empty result on invalid input).

**Comment by zainul-realtime** [comment]
Yeah ,thank you brother. No problem I think your library is pretty good. I will test it for the new branch ..
Thank you so much .
